//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.payments = new HashSet<payment>();
        }
    
        public int Reservation_Id { get; set; }
        public int Guest_Id { get; set; }
        public int Room_Id { get; set; }
        public System.DateTime Reservation_Date { get; set; }
        public Nullable<int> Members { get; set; }
        public System.DateTime Check_In_Date { get; set; }
        public System.DateTime Check_Out_Date { get; set; }
    
        public virtual Guest Guest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payments { get; set; }
        public virtual Room Room { get; set; }
    }
}
